### ISSUE TITLE
Custom Linux Build

### ISSUE THREAD

**Issue by charryshi** [LoveLH/Caddy_CustomBuild#25]
{"GOOS":"linux","GOARCH":"386","addons":"github.com/caddyserver/forwardproxy@caddy2=github.com/sagernet/forwardproxy@latest"}

**Comment by LoveLH** [comment]
似乎卡在了 github.com/sagernet/forwardproxy 的下载过程

**Comment by charryshi** [comment]
是的，后来我手工处理了。感谢
